image: gitpod/workspace-full

tasks:
  - name: Setup, Install & Run Node
    init: |
      curl -L https://foundry.paradigm.xyz | bash;
      PATH="$PATH:$HOME/.foundry/bin" foundryup;
      cargo install --locked just;
      cargo install --locked ldenv;
      PATH="$PATH:$HOME/.foundry/bin" just install;
    command: anvil

# Ports to expose on workspace startup
ports:
  - port: 8545
    onOpen: notify
    name: RPC
    description: NODE RPC
