image: gitpod/workspace-full

vscode:
  extensions:
    - NomicFoundation.hardhat-solidity
    # - Crisgarner.foundry-snippets
    # - praneshasp.vscode-foundry-test-adapter
    - tamasfe.even-better-toml

tasks:
  - name: Setup, Install & Run Node
    init: |
      curl -L https://foundry.paradigm.xyz | bash;
      PATH="$PATH:$HOME/.foundry/bin" foundryup;
      cp -R $HOME/.foundry/bin ./;
      cargo install --root . just;
      cargo install --root . ldenv;
      cargo install --root . watchexec-cli;
      PATH="$PATH:./bin" just reinstall;
    command: |
      echo "export PATH=\"\$PATH:./bin\"" >> ~/.bashrc;
      source ~/.bashrc;
      anvil

# Ports to expose on workspace startup
ports:
  - port: 8545
    name: RPC
    description: NODE RPC
