image: gitpod/workspace-full

vscode:
  extensions:
    - NomicFoundation.hardhat-solidity
    # - Crisgarner.foundry-snippets
    # - praneshasp.vscode-foundry-test-adapter
    - tamasfe.even-better-toml

tasks:
  - name: Setup, Install & Run Node
    init: |
      ./run install

      # + install watchexec
      cargo install --root . watchexec-cli;

      # move in home for gitpod prebuild
      mv $HOME/.foundry .foundry;
    command: |
      # move back
      mv .foundry $HOME/.foundry;

      # reexport the foundry PATH
      echo "export PATH=\"\$PATH:$HOME/.foundry/bin\"" >> ~/.bashrc;
      source ~/.bashrc;

      anvil

# Ports to expose on workspace startup
ports:
  - port: 8545
    name: RPC
    description: NODE RPC
