image:
  file: Dockerfile

tasks:
  - name: Install & Run Node
    before: just install
    init: just compile
    command: anvil

# Ports to expose on workspace startup
ports:
  - port: 8545
    onOpen: notify
    name: RPC
    description: NODE RPC
