image: gitpod/workspace-full

tasks:
  - name: Setup, Install & Run Node
    init: |
      curl -L https://foundry.paradigm.xyz | bash;
      PATH="$PATH:$HOME/.foundry/bin" foundryup;
      cp -R $HOME/.foundry/bin ./;
      cargo install --root . just;
      cargo install --root . ldenv;
      PATH="$PATH:./bin" just install;
    command: |
      echo "export PATH=\"\$PATH:./bin\"" >> ~/.bashrc;
      source ~/.bashrc;
      anvil

# Ports to expose on workspace startup
ports:
  - port: 8545
    onOpen: notify
    name: RPC
    description: NODE RPC
