image: gitpod/workspace-full

tasks:
  - name: Setup, Install & Run Node
    init: |
      ./run _setup_system
      ./run install

      # + install watchexec
      cargo install --root . watchexec-cli;
      cargo install --root . zellij;

      # move in home for gitpod prebuild
      mv $HOME/.foundry .foundry;
    command: |
      # move back
      mv .foundry $HOME/.foundry;

      # reexport the foundry PATH
      echo "export PATH=\"\$PATH:$HOME/.foundry/bin\"" >> ~/.bashrc;
      source ~/.bashrc;

      ./run start

# Ports to expose on workspace startup
ports:
  - port: 8545
    name: RPC
    description: NODE RPC
