[profile.default]
solc = "0.8.17" # keep in sync with .vscode/settings.json
src = "src"
out = "out"
libs = ["lib"]

[fmt]
ignore = ['generated/**/*.sol', "lib/**/*.sol"]

fs_permissions = [
    { access = "read", path = "./deployments" },
    { access = "read", path = "./out" },
    { access = "read", path = "./contexts.json" },
]
